### ISSUE TITLE
[CY-2527] Don't report common patterns used for test development

### ISSUE THREAD

**Issue by bittner** [codacy/codacy-bandit#30]
Codacy reports a few patterns, I would say falsely, that are very commonplace in test development.

## Examples

- "Use of assert detected" – _using `assert` is the main pattern when using [pytest](https://docs.pytest.org/en/latest/)_
- "Possible hardcoded password" – _making your test simple entails using hardcoded input values and testing the outcome in a hardcoded way again_ 
- "Starting a process with a partial executable path" – _mimicking the natural use of a CLI, for example_

## Sane Defaults vs. Custom Configuration

The result of Codacy's current defaults is that we have projects where 100% of the reported issues are in the test suite, e.g. https://app.codacy.com/manual/VSHN/concierge-cli/issues/index

I'm aware that Bandit has its own shortcomings (see https://github.com/PyCQA/bandit/issues/603) and the reported issues come directly from the tool. But given the fact that [you seem to run a custom approach](https://github.com/codacy/codacy-bandit/blob/master/src/main/scala/codacy/bandit/Bandit.scala#L98), you as a code quality platform should probably set the standards here (read: sane, intuitive defaults).

**Comment by josemiguelmelo** [comment]
Hi @bittner, ﻿

Thanks for the contribution and for letting us know about these patterns that are common in test development and that return false positives.

We followed your suggestion and, in order to prevent these false positives from being returned and improve our default configuration, we decided to remove these patterns from our list of default patterns for Bandit.

Thanks,
